apiVersion: v1
kind: ConfigMap
metadata:
  name: price-calc-config
data:
  quarkus.http.port: '8081'
  quarkus.kafka-streams.application-id: usd-eur-converter
  quarkus.kafka-streams.topics: usd-prices,eur-prices
  kafka-streams.cache.max.bytes.buffering: '10240'
  kafka-streams.commit.interval.ms: '1000'
  kafka-streams.metadata.max.age.ms: '500'
  kafka-streams.auto.offset.reset: earliest
  kafka-streams.metrics.recording.level: DEBUG
  kafka-streams.consumer.heartbeat.interval.ms: '200'
  kafka.bootstrap.servers: 'my-cluster-kafka-bootstrap:9092'
  kafka.security.protocol: PLAINTEXT
  #kafka.security.protocol=SASL_SSL
  
  #kafka.sasl.mechanism=OAUTHBEARER
  # kafka.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
  #   oauth.client.id="${CLIENT_ID}" \
  #   oauth.client.secret="${CLIENT_SECRET}" \
  #   oauth.token.endpoint.uri="${OAUTH_TOKEN_ENDPOINT_URI}" ;
  #kafka.sasl.login.callback.handler.class=io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
  kafka.sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule
  quarkus.kafka-streams.sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule