kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"mypricecalcimagestream:latest","namespace":"pricecalc2"},"fieldPath":"spec.template.spec.containers[?(@.name==\"pricecalc\")].image","pause":"false"}]
  name: pricecalc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricecalc
  template:
    metadata:
      labels:
        app: pricecalc
        deploymentconfig: pricecalc
    spec:
      containers:
        - name: pricecalc
          image: >-
            image-registry.openshift-image-registry.svc:5000/pricecalc2/mypricecalcimagestream
          ports:
            - name: 8080-tcp
              containerPort: 8080
              protocol: TCP
          env:
            - name: BOOTSTRAP_SERVER
              value: 'my-cluster-kafka-bootstrap.svc.cluster.local:9092'
          envFrom:
            - configMapRef:
                name: price-calc-config
          resources:
            limits:
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600